version: '3'

services:
  deno-rest:
    build: .
    image: deno-rest
    ports:
      - '9000:9000'
    restart: on-failure
    container_name: 'deno-rest'
    volumes:
      - ./data:/app/data
    networks:
      - network
    logging:
      options:
        max-size: '5k'

  p2p-cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: p2p-cron
    restart: on-failure
    container_name: 'p2p-cron'
    environment:
      - FETCH_INTERVAL=5
      - API_URL=http://deno-rest:9000
    networks:
      - network
    depends_on:
      - deno-rest
    logging:
      options:
        max-size: '10k'

networks:
  network:
    driver: bridge
